SET search_path TO app, public;

-- ============================================================
-- Location catalogs — countries → states → cities (hierarchical).
-- Seeded with Venezuela (ADR 0010: single market). Surrogate BIGINT
-- identity PKs + external uuid, soft-delete via is_active, audit columns.
-- ============================================================

-- ------------------------------------------------------------
-- countries: ISO 3166-1 — no external FKs
-- ------------------------------------------------------------
CREATE TABLE countries
(
    countries_id BIGINT       GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    uuid         UUID         NOT NULL UNIQUE DEFAULT gen_random_uuid(),
    iso_code     VARCHAR(2)   NOT NULL UNIQUE,          -- ISO 3166-1 alpha-2 (e.g. 'VE')
    name         VARCHAR(100) NOT NULL UNIQUE,
    is_active    BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    created_by   UUID,
    updated_by   UUID
);

CREATE INDEX idx_countries_is_active ON countries (is_active) WHERE is_active;

CREATE TRIGGER trg_countries_updated_at
    BEFORE UPDATE ON countries
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ------------------------------------------------------------
-- states: federal entities — depends on countries
-- ------------------------------------------------------------
CREATE TABLE states
(
    states_id  BIGINT       GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    uuid       UUID         NOT NULL UNIQUE DEFAULT gen_random_uuid(),
    country_id BIGINT       NOT NULL REFERENCES countries (countries_id),
    code       VARCHAR(10)  NOT NULL,                   -- ISO 3166-2 (e.g. 'VE-D')
    name       VARCHAR(100) NOT NULL,
    is_active  BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    created_by UUID,
    updated_by UUID,
    UNIQUE (country_id, code),
    UNIQUE (country_id, name)
);

CREATE INDEX idx_states_country_id ON states (country_id);
CREATE INDEX idx_states_is_active  ON states (is_active) WHERE is_active;

CREATE TRIGGER trg_states_updated_at
    BEFORE UPDATE ON states
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ------------------------------------------------------------
-- cities: municipalities / capitals — depends on states
-- ------------------------------------------------------------
CREATE TABLE cities
(
    cities_id  BIGINT       GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    uuid       UUID         NOT NULL UNIQUE DEFAULT gen_random_uuid(),
    state_id   BIGINT       NOT NULL REFERENCES states (states_id),
    name       VARCHAR(120) NOT NULL,
    is_active  BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    created_by UUID,
    updated_by UUID,
    UNIQUE (state_id, name)
);

CREATE INDEX idx_cities_state_id  ON cities (state_id);
CREATE INDEX idx_cities_is_active ON cities (is_active) WHERE is_active;

CREATE TRIGGER trg_cities_updated_at
    BEFORE UPDATE ON cities
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ============================================================
-- Seed — Venezuela
-- ============================================================

INSERT INTO countries (iso_code, name)
VALUES ('VE', 'Venezuela');


-- 24 entidades federales (23 estados + Distrito Capital). Las Dependencias
-- Federales (VE-W) se omiten: sin residentes afiliables. Códigos ISO 3166-2:VE.
INSERT INTO states (country_id, code, name)
SELECT c.countries_id, v.code, v.name
FROM countries c
CROSS JOIN (VALUES
    ('VE-Z', 'Amazonas'),
    ('VE-B', 'Anzoátegui'),
    ('VE-C', 'Apure'),
    ('VE-D', 'Aragua'),
    ('VE-E', 'Barinas'),
    ('VE-F', 'Bolívar'),
    ('VE-G', 'Carabobo'),
    ('VE-H', 'Cojedes'),
    ('VE-Y', 'Delta Amacuro'),
    ('VE-A', 'Distrito Capital'),
    ('VE-I', 'Falcón'),
    ('VE-J', 'Guárico'),
    ('VE-X', 'La Guaira'),
    ('VE-K', 'Lara'),
    ('VE-L', 'Mérida'),
    ('VE-M', 'Miranda'),
    ('VE-N', 'Monagas'),
    ('VE-O', 'Nueva Esparta'),
    ('VE-P', 'Portuguesa'),
    ('VE-R', 'Sucre'),
    ('VE-S', 'Táchira'),
    ('VE-T', 'Trujillo'),
    ('VE-U', 'Yaracuy'),
    ('VE-V', 'Zulia')
) AS v(code, name)
WHERE c.iso_code = 'VE';

-- Ciudades de Venezuela (486 en total, agrupadas por estado). Las de
-- Dependencias Federales se omiten (estado no modelado). Mapeo por código ISO.
INSERT INTO cities (state_id, name)
SELECT s.states_id, v.city
FROM states s
JOIN (VALUES
    ('VE-Z', 'Maroa'),
    ('VE-Z', 'Puerto Ayacucho'),
    ('VE-Z', 'San Fernando de Atabapo'),
    ('VE-B', 'Anaco'),
    ('VE-B', 'Aragua de Barcelona'),
    ('VE-B', 'Barcelona'),
    ('VE-B', 'Boca de Uchire'),
    ('VE-B', 'Cantaura'),
    ('VE-B', 'Clarines'),
    ('VE-B', 'El Chaparro'),
    ('VE-B', 'El Pao Anzoátegui'),
    ('VE-B', 'El Tigre'),
    ('VE-B', 'El Tigrito'),
    ('VE-B', 'Guanape'),
    ('VE-B', 'Guanta'),
    ('VE-B', 'Lechería'),
    ('VE-B', 'Onoto'),
    ('VE-B', 'Pariaguán'),
    ('VE-B', 'Píritu'),
    ('VE-B', 'Puerto La Cruz'),
    ('VE-B', 'Puerto Píritu'),
    ('VE-B', 'Sabana de Uchire'),
    ('VE-B', 'San Mateo Anzoátegui'),
    ('VE-B', 'San Pablo Anzoátegui'),
    ('VE-B', 'San Tomé'),
    ('VE-B', 'Santa Ana de Anzoátegui'),
    ('VE-B', 'Santa Fe Anzoátegui'),
    ('VE-B', 'Santa Rosa'),
    ('VE-B', 'Soledad'),
    ('VE-B', 'Urica'),
    ('VE-B', 'Valle de Guanape'),
    ('VE-C', 'Achaguas'),
    ('VE-C', 'Biruaca'),
    ('VE-C', 'Bruzual'),
    ('VE-C', 'El Amparo'),
    ('VE-C', 'El Nula'),
    ('VE-C', 'Elorza'),
    ('VE-C', 'Guasdualito'),
    ('VE-C', 'Mantecal'),
    ('VE-C', 'Puerto Páez'),
    ('VE-C', 'San Fernando de Apure'),
    ('VE-C', 'San Juan de Payara'),
    ('VE-D', 'Barbacoas'),
    ('VE-D', 'Cagua'),
    ('VE-D', 'Camatagua'),
    ('VE-D', 'Choroní'),
    ('VE-D', 'Colonia Tovar'),
    ('VE-D', 'El Consejo'),
    ('VE-D', 'La Victoria'),
    ('VE-D', 'Las Tejerías'),
    ('VE-D', 'Magdaleno'),
    ('VE-D', 'Maracay'),
    ('VE-D', 'Ocumare de La Costa'),
    ('VE-D', 'Palo Negro'),
    ('VE-D', 'San Casimiro'),
    ('VE-D', 'San Mateo'),
    ('VE-D', 'San Sebastián'),
    ('VE-D', 'Santa Cruz de Aragua'),
    ('VE-D', 'Tocorón'),
    ('VE-D', 'Turmero'),
    ('VE-D', 'Villa de Cura'),
    ('VE-D', 'Zuata'),
    ('VE-E', 'Barinas'),
    ('VE-E', 'Barinitas'),
    ('VE-E', 'Barrancas'),
    ('VE-E', 'Calderas'),
    ('VE-E', 'Capitanejo'),
    ('VE-E', 'Ciudad Bolivia'),
    ('VE-E', 'El Cantón'),
    ('VE-E', 'Las Veguitas'),
    ('VE-E', 'Libertad de Barinas'),
    ('VE-E', 'Sabaneta'),
    ('VE-E', 'Santa Bárbara de Barinas'),
    ('VE-E', 'Socopó'),
    ('VE-F', 'Caicara del Orinoco'),
    ('VE-F', 'Canaima'),
    ('VE-F', 'Ciudad Bolívar'),
    ('VE-F', 'Ciudad Piar'),
    ('VE-F', 'El Callao'),
    ('VE-F', 'El Dorado'),
    ('VE-F', 'El Manteco'),
    ('VE-F', 'El Palmar'),
    ('VE-F', 'El Pao'),
    ('VE-F', 'Guasipati'),
    ('VE-F', 'Guri'),
    ('VE-F', 'La Paragua'),
    ('VE-F', 'Matanzas'),
    ('VE-F', 'Puerto Ordaz'),
    ('VE-F', 'San Félix'),
    ('VE-F', 'Santa Elena de Uairén'),
    ('VE-F', 'Tumeremo'),
    ('VE-F', 'Unare'),
    ('VE-F', 'Upata'),
    ('VE-G', 'Bejuma'),
    ('VE-G', 'Belén'),
    ('VE-G', 'Campo de Carabobo'),
    ('VE-G', 'Canoabo'),
    ('VE-G', 'Central Tacarigua'),
    ('VE-G', 'Chirgua'),
    ('VE-G', 'Ciudad Alianza'),
    ('VE-G', 'El Palito'),
    ('VE-G', 'Guacara'),
    ('VE-G', 'Guigue'),
    ('VE-G', 'Las Trincheras'),
    ('VE-G', 'Los Guayos'),
    ('VE-G', 'Mariara'),
    ('VE-G', 'Miranda'),
    ('VE-G', 'Montalbán'),
    ('VE-G', 'Morón'),
    ('VE-G', 'Naguanagua'),
    ('VE-G', 'Puerto Cabello'),
    ('VE-G', 'San Joaquín'),
    ('VE-G', 'Tocuyito'),
    ('VE-G', 'Urama'),
    ('VE-G', 'Valencia'),
    ('VE-G', 'Vigirimita'),
    ('VE-H', 'Aguirre'),
    ('VE-H', 'Apartaderos Cojedes'),
    ('VE-H', 'Arismendi'),
    ('VE-H', 'Camuriquito'),
    ('VE-H', 'El Baúl'),
    ('VE-H', 'El Limón'),
    ('VE-H', 'El Pao Cojedes'),
    ('VE-H', 'El Socorro'),
    ('VE-H', 'La Aguadita'),
    ('VE-H', 'Las Vegas'),
    ('VE-H', 'Libertad de Cojedes'),
    ('VE-H', 'Mapuey'),
    ('VE-H', 'Piñedo'),
    ('VE-H', 'Samancito'),
    ('VE-H', 'San Carlos'),
    ('VE-H', 'Sucre'),
    ('VE-H', 'Tinaco'),
    ('VE-H', 'Tinaquillo'),
    ('VE-H', 'Vallecito'),
    ('VE-Y', 'Tucupita'),
    ('VE-A', 'Caracas'),
    ('VE-A', 'El Junquito'),
    ('VE-I', 'Adícora'),
    ('VE-I', 'Boca de Aroa'),
    ('VE-I', 'Cabure'),
    ('VE-I', 'Capadare'),
    ('VE-I', 'Capatárida'),
    ('VE-I', 'Chichiriviche'),
    ('VE-I', 'Churuguara'),
    ('VE-I', 'Coro'),
    ('VE-I', 'Cumarebo'),
    ('VE-I', 'Dabajuro'),
    ('VE-I', 'Judibana'),
    ('VE-I', 'La Cruz de Taratara'),
    ('VE-I', 'La Vela de Coro'),
    ('VE-I', 'Los Taques'),
    ('VE-I', 'Maparari'),
    ('VE-I', 'Mene de Mauroa'),
    ('VE-I', 'Mirimire'),
    ('VE-I', 'Pedregal'),
    ('VE-I', 'Píritu Falcón'),
    ('VE-I', 'Pueblo Nuevo Falcón'),
    ('VE-I', 'Puerto Cumarebo'),
    ('VE-I', 'Punta Cardón'),
    ('VE-I', 'Punto Fijo'),
    ('VE-I', 'San Juan de Los Cayos'),
    ('VE-I', 'San Luis'),
    ('VE-I', 'Santa Ana Falcón'),
    ('VE-I', 'Santa Cruz De Bucaral'),
    ('VE-I', 'Tocopero'),
    ('VE-I', 'Tocuyo de La Costa'),
    ('VE-I', 'Tucacas'),
    ('VE-I', 'Yaracal'),
    ('VE-J', 'Altagracia de Orituco'),
    ('VE-J', 'Cabruta'),
    ('VE-J', 'Calabozo'),
    ('VE-J', 'Camaguán'),
    ('VE-J', 'Chaguaramas Guárico'),
    ('VE-J', 'El Socorro'),
    ('VE-J', 'El Sombrero'),
    ('VE-J', 'Las Mercedes de Los Llanos'),
    ('VE-J', 'Lezama'),
    ('VE-J', 'Onoto'),
    ('VE-J', 'Ortíz'),
    ('VE-J', 'San José de Guaribe'),
    ('VE-J', 'San Juan de Los Morros'),
    ('VE-J', 'San Rafael de Laya'),
    ('VE-J', 'Santa María de Ipire'),
    ('VE-J', 'Tucupido'),
    ('VE-J', 'Valle de La Pascua'),
    ('VE-J', 'Zaraza'),
    ('VE-K', 'Aguada Grande'),
    ('VE-K', 'Atarigua'),
    ('VE-K', 'Barquisimeto'),
    ('VE-K', 'Bobare'),
    ('VE-K', 'Cabudare'),
    ('VE-K', 'Carora'),
    ('VE-K', 'Cubiro'),
    ('VE-K', 'Cují'),
    ('VE-K', 'Duaca'),
    ('VE-K', 'El Manzano'),
    ('VE-K', 'El Tocuyo'),
    ('VE-K', 'Guaríco'),
    ('VE-K', 'Humocaro Alto'),
    ('VE-K', 'Humocaro Bajo'),
    ('VE-K', 'La Miel'),
    ('VE-K', 'Moroturo'),
    ('VE-K', 'Quíbor'),
    ('VE-K', 'Río Claro'),
    ('VE-K', 'Sanare'),
    ('VE-K', 'Santa Inés'),
    ('VE-K', 'Sarare'),
    ('VE-K', 'Siquisique'),
    ('VE-K', 'Tintorero'),
    ('VE-L', 'Apartaderos Mérida'),
    ('VE-L', 'Arapuey'),
    ('VE-L', 'Bailadores'),
    ('VE-L', 'Caja Seca'),
    ('VE-L', 'Canaguá'),
    ('VE-L', 'Chachopo'),
    ('VE-L', 'Chiguara'),
    ('VE-L', 'Ejido'),
    ('VE-L', 'El Vigía'),
    ('VE-L', 'La Azulita'),
    ('VE-L', 'La Playa'),
    ('VE-L', 'Lagunillas Mérida'),
    ('VE-L', 'Mérida'),
    ('VE-L', 'Mesa de Bolívar'),
    ('VE-L', 'Mucuchíes'),
    ('VE-L', 'Mucujepe'),
    ('VE-L', 'Mucuruba'),
    ('VE-L', 'Nueva Bolivia'),
    ('VE-L', 'Palmarito'),
    ('VE-L', 'Pueblo Llano'),
    ('VE-L', 'Santa Cruz de Mora'),
    ('VE-L', 'Santa Elena de Arenales'),
    ('VE-L', 'Santo Domingo'),
    ('VE-L', 'Tabáy'),
    ('VE-L', 'Timotes'),
    ('VE-L', 'Torondoy'),
    ('VE-L', 'Tovar'),
    ('VE-L', 'Tucani'),
    ('VE-L', 'Zea'),
    ('VE-M', 'Araguita'),
    ('VE-M', 'Carrizal'),
    ('VE-M', 'Caucagua'),
    ('VE-M', 'Chaguaramas Miranda'),
    ('VE-M', 'Charallave'),
    ('VE-M', 'Chirimena'),
    ('VE-M', 'Chuspa'),
    ('VE-M', 'Cúa'),
    ('VE-M', 'Cupira'),
    ('VE-M', 'Curiepe'),
    ('VE-M', 'El Guapo'),
    ('VE-M', 'El Jarillo'),
    ('VE-M', 'Filas de Mariche'),
    ('VE-M', 'Guarenas'),
    ('VE-M', 'Guatire'),
    ('VE-M', 'Higuerote'),
    ('VE-M', 'Los Anaucos'),
    ('VE-M', 'Los Teques'),
    ('VE-M', 'Ocumare del Tuy'),
    ('VE-M', 'Panaquire'),
    ('VE-M', 'Paracotos'),
    ('VE-M', 'Río Chico'),
    ('VE-M', 'San Antonio de Los Altos'),
    ('VE-M', 'San Diego de Los Altos'),
    ('VE-M', 'San Fernando del Guapo'),
    ('VE-M', 'San Francisco de Yare'),
    ('VE-M', 'San José de Los Altos'),
    ('VE-M', 'San José de Río Chico'),
    ('VE-M', 'San Pedro de Los Altos'),
    ('VE-M', 'Santa Lucía'),
    ('VE-M', 'Santa Teresa'),
    ('VE-M', 'Tacarigua de La Laguna'),
    ('VE-M', 'Tacarigua de Mamporal'),
    ('VE-M', 'Tácata'),
    ('VE-M', 'Turumo'),
    ('VE-N', 'Aguasay'),
    ('VE-N', 'Aragua de Maturín'),
    ('VE-N', 'Barrancas del Orinoco'),
    ('VE-N', 'Caicara de Maturín'),
    ('VE-N', 'Caripe'),
    ('VE-N', 'Caripito'),
    ('VE-N', 'Chaguaramal'),
    ('VE-N', 'Chaguaramas Monagas'),
    ('VE-N', 'El Furrial'),
    ('VE-N', 'El Tejero'),
    ('VE-N', 'Jusepín'),
    ('VE-N', 'La Toscana'),
    ('VE-N', 'Maturín'),
    ('VE-N', 'Miraflores'),
    ('VE-N', 'Punta de Mata'),
    ('VE-N', 'Quiriquire'),
    ('VE-N', 'San Antonio de Maturín'),
    ('VE-N', 'San Vicente Monagas'),
    ('VE-N', 'Santa Bárbara'),
    ('VE-N', 'Temblador'),
    ('VE-N', 'Teresen'),
    ('VE-N', 'Uracoa'),
    ('VE-O', 'Altagracia'),
    ('VE-O', 'Boca de Pozo'),
    ('VE-O', 'Boca de Río'),
    ('VE-O', 'El Espinal'),
    ('VE-O', 'El Valle del Espíritu Santo'),
    ('VE-O', 'El Yaque'),
    ('VE-O', 'Juangriego'),
    ('VE-O', 'La Asunción'),
    ('VE-O', 'La Guardia'),
    ('VE-O', 'Pampatar'),
    ('VE-O', 'Porlamar'),
    ('VE-O', 'Puerto Fermín'),
    ('VE-O', 'Punta de Piedras'),
    ('VE-O', 'San Francisco de Macanao'),
    ('VE-O', 'San Juan Bautista'),
    ('VE-O', 'San Pedro de Coche'),
    ('VE-O', 'Santa Ana de Nueva Esparta'),
    ('VE-O', 'Villa Rosa'),
    ('VE-P', 'Acarigua'),
    ('VE-P', 'Agua Blanca'),
    ('VE-P', 'Araure'),
    ('VE-P', 'Biscucuy'),
    ('VE-P', 'Boconoito'),
    ('VE-P', 'Campo Elías'),
    ('VE-P', 'Chabasquén'),
    ('VE-P', 'Guanare'),
    ('VE-P', 'Guanarito'),
    ('VE-P', 'La Aparición'),
    ('VE-P', 'La Misión'),
    ('VE-P', 'Mesa de Cavacas'),
    ('VE-P', 'Ospino'),
    ('VE-P', 'Papelón'),
    ('VE-P', 'Payara'),
    ('VE-P', 'Pimpinela'),
    ('VE-P', 'Píritu de Portuguesa'),
    ('VE-P', 'San Rafael de Onoto'),
    ('VE-P', 'Santa Rosalía'),
    ('VE-P', 'Turén'),
    ('VE-R', 'Altos de Sucre'),
    ('VE-R', 'Araya'),
    ('VE-R', 'Cariaco'),
    ('VE-R', 'Carúpano'),
    ('VE-R', 'Casanay'),
    ('VE-R', 'Cumaná'),
    ('VE-R', 'Cumanacoa'),
    ('VE-R', 'El Morro Puerto Santo'),
    ('VE-R', 'El Pilar'),
    ('VE-R', 'El Poblado'),
    ('VE-R', 'Guaca'),
    ('VE-R', 'Guiria'),
    ('VE-R', 'Irapa'),
    ('VE-R', 'Manicuare'),
    ('VE-R', 'Mariguitar'),
    ('VE-R', 'Río Caribe'),
    ('VE-R', 'San Antonio del Golfo'),
    ('VE-R', 'San José de Aerocuar'),
    ('VE-R', 'San Vicente de Sucre'),
    ('VE-R', 'Santa Fe de Sucre'),
    ('VE-R', 'Tunapuy'),
    ('VE-R', 'Yaguaraparo'),
    ('VE-R', 'Yoco'),
    ('VE-S', 'Abejales'),
    ('VE-S', 'Borota'),
    ('VE-S', 'Bramon'),
    ('VE-S', 'Capacho'),
    ('VE-S', 'Colón'),
    ('VE-S', 'Coloncito'),
    ('VE-S', 'Cordero'),
    ('VE-S', 'El Cobre'),
    ('VE-S', 'El Pinal'),
    ('VE-S', 'Independencia'),
    ('VE-S', 'La Fría'),
    ('VE-S', 'La Grita'),
    ('VE-S', 'La Pedrera'),
    ('VE-S', 'La Tendida'),
    ('VE-S', 'Las Delicias'),
    ('VE-S', 'Las Hernández'),
    ('VE-S', 'Lobatera'),
    ('VE-S', 'Michelena'),
    ('VE-S', 'Palmira'),
    ('VE-S', 'Pregonero'),
    ('VE-S', 'Queniquea'),
    ('VE-S', 'Rubio'),
    ('VE-S', 'San Antonio del Tachira'),
    ('VE-S', 'San Cristobal'),
    ('VE-S', 'San José de Bolívar'),
    ('VE-S', 'San Josecito'),
    ('VE-S', 'San Pedro del Río'),
    ('VE-S', 'Santa Ana Táchira'),
    ('VE-S', 'Seboruco'),
    ('VE-S', 'Táriba'),
    ('VE-S', 'Umuquena'),
    ('VE-S', 'Ureña'),
    ('VE-T', 'Batatal'),
    ('VE-T', 'Betijoque'),
    ('VE-T', 'Boconó'),
    ('VE-T', 'Carache'),
    ('VE-T', 'Chejende'),
    ('VE-T', 'Cuicas'),
    ('VE-T', 'El Dividive'),
    ('VE-T', 'El Jaguito'),
    ('VE-T', 'Escuque'),
    ('VE-T', 'Isnotú'),
    ('VE-T', 'Jajó'),
    ('VE-T', 'La Ceiba'),
    ('VE-T', 'La Concepción de Trujllo'),
    ('VE-T', 'La Mesa de Esnujaque'),
    ('VE-T', 'La Puerta'),
    ('VE-T', 'La Quebrada'),
    ('VE-T', 'Mendoza Fría'),
    ('VE-T', 'Meseta de Chimpire'),
    ('VE-T', 'Monay'),
    ('VE-T', 'Motatán'),
    ('VE-T', 'Pampán'),
    ('VE-T', 'Pampanito'),
    ('VE-T', 'Sabana de Mendoza'),
    ('VE-T', 'San Lázaro'),
    ('VE-T', 'Santa Ana de Trujillo'),
    ('VE-T', 'Tostós'),
    ('VE-T', 'Trujillo'),
    ('VE-T', 'Valera'),
    ('VE-X', 'Carayaca'),
    ('VE-X', 'Litoral'),
    ('VE-U', 'Aroa'),
    ('VE-U', 'Boraure'),
    ('VE-U', 'Campo Elías de Yaracuy'),
    ('VE-U', 'Chivacoa'),
    ('VE-U', 'Cocorote'),
    ('VE-U', 'Farriar'),
    ('VE-U', 'Guama'),
    ('VE-U', 'Marín'),
    ('VE-U', 'Nirgua'),
    ('VE-U', 'Sabana de Parra'),
    ('VE-U', 'Salom'),
    ('VE-U', 'San Felipe'),
    ('VE-U', 'San Pablo de Yaracuy'),
    ('VE-U', 'Urachiche'),
    ('VE-U', 'Yaritagua'),
    ('VE-U', 'Yumare'),
    ('VE-V', 'Bachaquero'),
    ('VE-V', 'Bobures'),
    ('VE-V', 'Cabimas'),
    ('VE-V', 'Campo Concepción'),
    ('VE-V', 'Campo Mara'),
    ('VE-V', 'Campo Rojo'),
    ('VE-V', 'Carrasquero'),
    ('VE-V', 'Casigua'),
    ('VE-V', 'Chiquinquirá'),
    ('VE-V', 'Ciudad Ojeda'),
    ('VE-V', 'El Batey'),
    ('VE-V', 'El Carmelo'),
    ('VE-V', 'El Chivo'),
    ('VE-V', 'El Guayabo'),
    ('VE-V', 'El Mene'),
    ('VE-V', 'El Venado'),
    ('VE-V', 'Encontrados'),
    ('VE-V', 'Gibraltar'),
    ('VE-V', 'Isla de Toas'),
    ('VE-V', 'La Concepción del Zulia'),
    ('VE-V', 'La Paz'),
    ('VE-V', 'La Sierrita'),
    ('VE-V', 'Lagunillas del Zulia'),
    ('VE-V', 'Las Piedras de Perijá'),
    ('VE-V', 'Los Cortijos'),
    ('VE-V', 'Machiques'),
    ('VE-V', 'Maracaibo'),
    ('VE-V', 'Mene Grande'),
    ('VE-V', 'Palmarejo'),
    ('VE-V', 'Paraguaipoa'),
    ('VE-V', 'Potrerito'),
    ('VE-V', 'Pueblo Nuevo del Zulia'),
    ('VE-V', 'Puertos de Altagracia'),
    ('VE-V', 'Punta Gorda'),
    ('VE-V', 'Sabaneta de Palma'),
    ('VE-V', 'San Francisco'),
    ('VE-V', 'San José de Perijá'),
    ('VE-V', 'San Rafael del Moján'),
    ('VE-V', 'San Timoteo'),
    ('VE-V', 'Santa Bárbara Del Zulia'),
    ('VE-V', 'Santa Cruz de Mara'),
    ('VE-V', 'Santa Cruz del Zulia'),
    ('VE-V', 'Santa Rita'),
    ('VE-V', 'Sinamaica'),
    ('VE-V', 'Tamare'),
    ('VE-V', 'Tía Juana'),
    ('VE-V', 'Villa del Rosario'),
    ('VE-X', 'La Guaira'),
    ('VE-X', 'Catia La Mar'),
    ('VE-X', 'Macuto'),
    ('VE-X', 'Naiguatá')
) AS v(state_code, city) ON v.state_code = s.code;
